M48
; DRILL file {KiCad 9.0.0} date 2025-05-12T21:33:36-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-12T21:33:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1880
%
G90
G05
T1
X3.1819Y-5.4406
T2
X3.1819Y-3.0906
M30
